# coding = utf-8

'''
此文件为测试套件
'''
import unittest
from TestPython.api import Assertion


def Suite():
    suite = unittest.TestSuite()
    # suite.addTest(Assertion.tripApiTest("test_tripSuccuss"))
    # suite.addTest(Assertion.tripApiTest("test_tripIDNone"))
    # suite.addTest(Assertion.tripApiTest("test_tripSTNone"))
    # suite.addTest(Assertion.tripApiTest("test_tripETNone"))
    # suite.addTest(Assertion.tripApiTest("test_tripIdEmpty"))
    # suite.addTest(Assertion.tripApiTest("test_tripSTEmpty"))
    # suite.addTest(Assertion.tripApiTest("test_tripETEmpty"))
    # suite.addTest(Assertion.tripApiTest("test_tripNoID"))
    # suite.addTest(Assertion.tripApiTest("test_tripNoST"))
    # suite.addTest(Assertion.tripApiTest("test_tripNoET"))

    suite.addTest(Assertion.loginApiTest("test_loginSuccess"))
    suite.addTest(Assertion.loginApiTest("test_loginUserErrorOrPwdError"))
    suite.addTest(Assertion.loginApiTest("test_loginNoActive"))
    suite.addTest(Assertion.loginApiTest("test_loginUserNone"))
    suite.addTest(Assertion.loginApiTest("test_loginPwdNone"))
    suite.addTest(Assertion.loginApiTest("test_loginNoUser"))
    suite.addTest(Assertion.loginApiTest("test_loginNoPwd"))
    suite.addTest(Assertion.loginApiTest("test_loginUserEmpty"))
    suite.addTest(Assertion.loginApiTest("test_loginPwdEmpty"))

    # suite.addTest(Assertion.logoutApiTest("test_logoutFail"))
    # suite.addTest(Assertion.logoutApiTest("test_logoutSuccess"))

    # suite.addTest(Assertion.emailApiTest("test_resetUnregistered"))
    # suite.addTest(Assertion.emailApiTest("test_resetNone"))
    # suite.addTest(Assertion.emailApiTest("test_resetEmpty"))
    # suite.addTest(Assertion.emailApiTest("test_resetInvalidFormat"))
    # suite.addTest(Assertion.emailApiTest("test_resetNotfound"))
    # suite.addTest(Assertion.emailApiTest("test_resetNoEmail"))
    # suite.addTest(Assertion.emailApiTest("test_resetSuccess"))

    # suite.addTest(Assertion.resetApiTest("test_resetInvalid"))
    # suite.addTest(Assertion.resetApiTest("test_resetWrongCF"))
    # suite.addTest(Assertion.resetApiTest("test_resetPwdIllegal"))
    # suite.addTest(Assertion.resetApiTest("test_resetCFNone"))
    # suite.addTest(Assertion.resetApiTest("test_resetPwdNone"))
    # suite.addTest(Assertion.resetApiTest("test_resetCFEmpty"))
    # suite.addTest(Assertion.resetApiTest("test_resetPwdEmpty"))
    # suite.addTest(Assertion.resetApiTest("test_resetPwdless"))
    # suite.addTest(Assertion.resetApiTest("test_resetPwdMin"))
    # suite.addTest(Assertion.resetApiTest("test_resetPwdMax"))
    # suite.addTest(Assertion.resetApiTest("test_resetPwdOut"))
    # suite.addTest(Assertion.resetApiTest("test_resetPwdInt"))
    # suite.addTest(Assertion.resetApiTest("test_resetSuccess"))


    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoCookie"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserSuccess"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserENone"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserFNNONE"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserLNNone"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserATNone"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserMNone"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserPwdNone"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserRIdNone"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserTidsNone"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserEEmpty"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserFNEmpty"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserLNEmpty"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserATEmpty"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserMEmpty"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserPwdEmpty"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserRIdEmpty"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserTidsEmpty"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoEmail"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoFN"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoLN"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoAT"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoM"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoPwd"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoRId"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserNoTids"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserAEmailError"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserUEmailError"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserEFormError"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserFNOut"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserLNOut"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserMEOut"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserPwdOut"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserPwdLess"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserFNMax"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserLNMax"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserMEMax"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserPwdMax"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserPwdMin"))
    suite.addTest(Assertion.AdduserApiTest("test_AdduserRIdError"))

    # suite.addTest(Assertion.userManagementApiTest("test_userSuccess"))
    # suite.addTest(Assertion.userManagementApiTest("test_userNoCookie"))
    #
    # suite.addTest(Assertion.user_idApiTest("oneuserSuccess"))
    # suite.addTest(Assertion.user_idApiTest("oneuserNocookie"))
    #
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserNoCookie"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserENone"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserFNNONE"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserLNNone"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserATNone"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserRIdNone"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserTidsNone"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserEEmpty"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserFNEmpty"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserLNEmpty"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserATEmpty"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserMEmpty"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserRIdEmpty"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserTidsEmpty"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserAEmailError"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserUEmailError"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserEFormError"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituseFNMax"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserLNMax"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserMEMax"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserRIdError"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserESuccess"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserFNSuccess"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserLNSuccess"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserATSuccess"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserMSuccess"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserRIdSuccess"))
    # suite.addTest(Assertion.EdituserApiTest("test_EdituserTidsSuccess"))
    #
    # suite.addTest(Assertion.DeleteUserApiTest("test_deleteUserSuccess"))
    # suite.addTest(Assertion.DeleteUserApiTest("test_deleteUserNocookie"))

    # suite.addTest(Assertion.timelineApiTest("test_timelineNoCookie"))
    # suite.addTest(Assertion.timelineApiTest("test_timelineNoCookie"))
    # suite.addTest(Assertion.timelineApiTest("test_timelineNoCookie"))
    # suite.addTest(Assertion.timelineApiTest("test_timelineNoCookie"))
    # suite.addTest(Assertion.timelineApiTest("test_timelineNoCookie"))

    # timeline没有写
    # suite.addTest(Assertion.timelineApiTest("test_timelineNoCookie"))

    suite.addTest(Assertion.permissionsApiTest("test_roleSuccess"))
    suite.addTest(Assertion.permissionsApiTest("test_roleNocookie"))

    suite.addTest(Assertion.userroleApiTest("test_userroleSuccess"))
    suite.addTest(Assertion.userroleApiTest("test_userroleNocookie"))

    suite.addTest(Assertion.AddroleApiTest("test_addroleSuccess"))
    suite.addTest(Assertion.AddroleApiTest("test_addroleNocookie"))
    suite.addTest(Assertion.AddroleApiTest("test_addroleOnly"))
    suite.addTest(Assertion.AddroleApiTest("test_addroleNMEmpty"))
    suite.addTest(Assertion.AddroleApiTest("test_addrolePMSEmpty"))
    suite.addTest(Assertion.AddroleApiTest("test_addroleNMNone"))
    suite.addTest(Assertion.AddroleApiTest("test_addrolePMSNone"))
    suite.addTest(Assertion.AddroleApiTest("test_addroleNoNM"))
    suite.addTest(Assertion.AddroleApiTest("test_addroleNoPMS"))
    suite.addTest(Assertion.AddroleApiTest("test_addroleNMInt"))
    suite.addTest(Assertion.AddroleApiTest("test_addrolePMSStr"))

    suite.addTest(Assertion.role_idApiTest("test_oneroleSuccess"))
    suite.addTest(Assertion.role_idApiTest("test_oneroleNocookie"))

    suite.addTest(Assertion.EditroleApiTest("test_roleNocookie"))
    suite.addTest(Assertion.EditroleApiTest("test_rolenameSuccess"))
    suite.addTest(Assertion.EditroleApiTest("test_rolePMSSuccess"))
    suite.addTest(Assertion.EditroleApiTest("test_rolePMSNothing"))
    suite.addTest(Assertion.EditroleApiTest("test_rolenameNone"))
    suite.addTest(Assertion.EditroleApiTest("test_rolePMSNone"))
    suite.addTest(Assertion.EditroleApiTest("test_rolenameEmpty"))
    suite.addTest(Assertion.EditroleApiTest("test_rolePMSEmpty"))
    suite.addTest(Assertion.EditroleApiTest("test_rolenameInt"))
    suite.addTest(Assertion.EditroleApiTest("test_rolePMSStr"))

    suite.addTest(Assertion.deleteroleApiTest("test_roleNocookie"))
    suite.addTest(Assertion.deleteroleApiTest("test_roleDeleteSuccess"))

    suite.addTest(Assertion.poisApiTest("test_poisNocookie"))
    suite.addTest(Assertion.poisApiTest("test_poisSuccess"))
    suite.addTest(Assertion.poisApiTest("test_poisNoPage"))
    suite.addTest(Assertion.poisApiTest("test_poisNoPSiza"))
    suite.addTest(Assertion.poisApiTest("test_poisEmpty"))
    suite.addTest(Assertion.poisApiTest("test_poisPSizaEmpty"))
    suite.addTest(Assertion.poisApiTest("test_poisNone"))
    suite.addTest(Assertion.poisApiTest("test_poisPSizaNone"))
    suite.addTest(Assertion.poisApiTest("test_poisStr"))
    suite.addTest(Assertion.poisApiTest("test_poisPSStr"))
    suite.addTest(Assertion.poisApiTest("test_poisPageNoExist"))
    suite.addTest(Assertion.poisApiTest("test_poisPSizeNoExist"))

    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNocookie"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiSuccess"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiSuccessNoalert"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNameEmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiARSEmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiPathEmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiREmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiLtEmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiLgEmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiEAEmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiOAEmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoitidsEmpty"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNameNone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiARSNone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiPathNone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiRNone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiLtNone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiLgNone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiEANone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiOANone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoitidsNone"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoname"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoaddress"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoAP"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoR"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoLT"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoLG"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoaEA"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoOA"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNoTids"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiNameInt"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiRStr"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiLtStr"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiLgStr"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiEAStr"))
    suite.addTest(Assertion.AddpoiApiTest("test_AddpoiOAStr"))

    suite.addTest(Assertion.EditPOIApiTest("test_EditPOINocookie"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOINameSuccess"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIAPSuccess"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIEASuccess"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIOASuccess"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOITidsSuccess"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOINameEmpty"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIPathEmpty"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIEAEmpty"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIOAEmpty"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOItidsEmpty"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOINameNone"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIPathNone"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIEANone"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIOANone"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOItidsNone"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOINameInt"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIEAStr"))
    suite.addTest(Assertion.EditPOIApiTest("test_EditPOIOAStr"))

    # 删除poi
    suite.addTest(Assertion.deletepoiApiTest("test_deletePoiNocookie"))
    suite.addTest(Assertion.deletepoiApiTest("test_deletePoiSuccess"))

    # 获取围栏列表
    suite.addTest(Assertion.GEOApiTest("test_geoNocookie"))
    suite.addTest(Assertion.GEOApiTest("test_geoSuccess"))
    suite.addTest(Assertion.GEOApiTest("test_geoNoPage"))
    suite.addTest(Assertion.GEOApiTest("test_geoNoPSiza"))
    suite.addTest(Assertion.GEOApiTest("test_geoEmpty"))
    suite.addTest(Assertion.GEOApiTest("test_geoPSizaEmpty"))
    suite.addTest(Assertion.GEOApiTest("test_geoNone"))
    suite.addTest(Assertion.GEOApiTest("test_geoPSizaNone"))
    suite.addTest(Assertion.GEOApiTest("test_geoStr"))
    suite.addTest(Assertion.GEOApiTest("test_geoPSStr"))

    suite.addTest(Assertion.AddgeoApiTest("test_geoNocookie"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoCircleSuccess"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoPolygonSuccess"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoNameRepeat"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoNameMin"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoNameMax"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoNameEmpty"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoNameNone"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoNameInt"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoNameNo"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoShapeNoExist"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoShapeStr"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoShapeEmpty"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoShapeNone"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoShapeIncorrect"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoShapeNo"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoPolygonEmpty"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoCicleEmpty"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoPolygonNone"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoCicleNone"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoTypeInvalid"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoTypeNo"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoEnterAlert0"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoEnterAlertNoExist"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoEnterAlertStr"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoEnterAlertEmpty"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoEnterAlertNone"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoEnterAlertNo"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoOutAlert0"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoOutAlertNoExist"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoOutAlertStr"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoOutAlertEmpty"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoOutAlertNone"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoOutAlertNo"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoSchedule2"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoSchedule3"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoSchedule4"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoScheduleEmpty"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoScheduleNone"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoScheduleNo"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoTidNoNotifications"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoTidStr"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoTidEmpty"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoTidNoExist"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoTidNone"))
    suite.addTest(Assertion.AddgeoApiTest("test_geoTidNo"))

    suite.addTest(Assertion.EditgeoApiTest("test_regionEditFail"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditNoParam"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditNameMin"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditNameRepeat"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditNameMax"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditNameOut"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditNameEmpty"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditNameNone"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditNameInt"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditShapeNoExist"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditShapeStr"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditShapeEmpty"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditShapeNone"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditShapeIncorrect"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditPolygonEmpty"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditCicleEmpty"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditPolygonNone"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditCicleNone"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditTypeInvalid"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditEnterAlert0"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditEnterAlertNoExist"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditEnterAlertStr"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditEnterAlertEmpty"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditEnterAlertNone"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditOutAlert0"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditOutAlertNoExist"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditOutAlertStr"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditOutAlertEmpty"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditOutAlertNone"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditSchedule2"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditSchedule3"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditSchedule4"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditScheduleEmpty"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditScheduleNone"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditTidNoNotifications"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditTidStr"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditTidEmpty"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditTidNoExist"))
    suite.addTest(Assertion.EditgeoApiTest("test_regionEditTidNone"))

    suite.addTest(Assertion.deletegeoApiTest("test_deletegeoNocookie"))
    suite.addTest(Assertion.deletegeoApiTest("test_deletegeoSuccess"))

    suite.addTest(Assertion.notificationApiTest("test_notificationNocookie"))
    suite.addTest(Assertion.notificationApiTest("test_notificationSuccess"))
    return suite
